# experiment
model: bert_vae # speaker_prompt, prefix_tuning, bert_vae
experiment_name: 17june_bert_vae_latent100_kl1000_cycanneal_maxseqlen256_batch8_8_lr1e5 # prefix_tuning_spt or prefix_tuning_pp

# directory info
data_path: /cluster/scratch/goezsoy/nlp_lss_datasets
log_dir: ../logs
checkpoint_dir: /cluster/scratch/goezsoy/nlp_lss_checkpoints

# training
epochs: 10
max_seq_len: 256
batch_size: 8
gradient_accumulations: 8  # batch_size * gr_acc = effective batch size
learning_rate: 0.00001 # 1e-5?
print_iter_freq: 100
#early_stopping: True  # fix
#lr_scheduling: True  # fix

# generation
#do_sample: True
#temperature: 0.9
#max_length: 200

# prefix tuning
prefix_len: 10
embed_size_per_token: 500
speaker_size: 28 #800 or 106 or 28
freeze_gpt: False
encoded: 'encoded_parl_part_ids' # 'encoded_bioguide_ids' or 'encoded_st_p_ids' or 'encoded_parl_part_ids'

# bert_vae
latent_dim: 100
kl_weight: 1000.0
use_annealing: True
annealing_period: 200