# experiment
experiment_name: speaker_name_as_prompt_deneme

# directory info
data_path: /cluster/scratch/goezsoy/nlp_lss_datasets/processed_df.csv
log_dir: '../logs'
checkpoint_dir: '../checkpoints'

# training
epochs: 5
max_seq_len: 256 
batch_size: 8
gradient_accumulations: 8  # batch_size * gr_acc = effective batch size
learning_rate: 0.0001 # 1e-5?
#early_stopping: True  # fix
#lr_scheduling: True  # fix

# generation
#do_sample: True
#temperature: 0.9
#max_length: 200