# experiment
experiment_name: 18may_speaker_name_following_lr00002_seqlen256_batch_8_8

# directory info
data_path: /cluster/scratch/goezsoy/nlp_lss_datasets
log_dir: ../logs
checkpoint_dir: /cluster/scratch/goezsoy/nlp_lss_checkpoints

# training
epochs: 10
max_seq_len: 256
batch_size: 8
gradient_accumulations: 8  # batch_size * gr_acc = effective batch size
learning_rate: 0.00002 # 1e-5?
print_iter_freq: 500
#early_stopping: True  # fix
#lr_scheduling: True  # fix

# generation
#do_sample: True
#temperature: 0.9
#max_length: 200